<?php
/**
 * Shared football "story" dataset for the Participating Teams Map.
 *
 * Keyed by the same ISO flag codes used in _teams_map.php (wc_tm_country_code).
 * Each entry carries:
 *   confed   - confederation tag (UEFA / CONMEBOL / CONCACAF / CAF / AFC / OFC)
 *   story    - short football story (English)
 *   story_ar - same, Arabic
 *   stars    - notable players (universal Latin names)
 *   moments  - key World-Cup / football moments (English short bullets)
 *
 * The home + matches map popups and the full Teams-Map page all read this,
 * so every qualified nation shows real detail when tapped (not just a name).
 */

if (!function_exists('wc_team_meta')) {
    function wc_team_meta(string $code = ''): array {
        static $m = null;
        if ($m === null) {
            $m = [
                /* ---- Hosts / CONCACAF ---- */
                'us' => ['confed'=>'CONCACAF','story'=>'Co-host in 2026 and a fast-rising side built on a European-based golden generation.','story_ar'=>'مستضيف مشارك 2026 ومنتخب صاعد بسرعة يعتمد على جيل ذهبي يحترف في أوروبا.','stars'=>['Christian Pulisic','Weston McKennie','Gio Reyna'],'moments'=>['Reached the 2002 World Cup quarter-finals','Back-to-back Nations League & Gold Cup runs']],
                'ca' => ['confed'=>'CONCACAF','story'=>'Co-host in 2026, back on the world stage with their most talented squad ever.','story_ar'=>'مستضيف مشارك 2026، يعود إلى الساحة العالمية بأفضل تشكيلة في تاريخه.','stars'=>['Alphonso Davies','Jonathan David','Cyle Larin'],'moments'=>['Topped CONCACAF qualifying for 2022','First World Cup goal scored in 2022 by Alphonso Davies']],
                'mx' => ['confed'=>'CONCACAF','story'=>'Co-host and a CONCACAF powerhouse famous for reaching the last 16 time after time.','story_ar'=>'مستضيف مشارك وقوة في الكونكاكاف اشتهر بالوصول إلى دور الـ16 مراراً.','stars'=>['Santiago Giménez','Edson Álvarez','Hirving Lozano'],'moments'=>['Quarter-finalists as hosts in 1970 and 1986','Beat reigning champions Germany in 2018']],
                'cr' => ['confed'=>'CONCACAF','story'=>'The pride of Central America, famous for a fearless run to the 2014 quarter-finals.','story_ar'=>'فخر أمريكا الوسطى، اشتهر بمسيرة جريئة إلى ربع نهائي 2014.','stars'=>['Keylor Navas','Manfred Ugalde'],'moments'=>['Topped a group of England, Italy & Uruguay in 2014','Reached the quarter-finals in 2014']],
                'pa' => ['confed'=>'CONCACAF','story'=>'A spirited side that celebrated its first-ever World Cup appearance in 2018.','story_ar'=>'منتخب متحمّس احتفل بأول ظهور له في كأس العالم 2018.','stars'=>['Adalberto Carrasquilla','José Fajardo'],'moments'=>['Qualified for a first World Cup in 2018','Roman Torres goal sealed historic qualification']],
                'jm' => ['confed'=>'CONCACAF','story'=>'The Reggae Boyz, whose 1998 debut remains a landmark for Caribbean football.','story_ar'=>'فتيان الريغي، وظهورهم الأول عام 1998 يبقى علامة فارقة لكرة الكاريبي.','stars'=>['Leon Bailey','Michail Antonio'],'moments'=>['First Caribbean nation to qualify in 1998','Beat Japan at France 98']],
                'hn' => ['confed'=>'CONCACAF','story'=>'Honduras have brought passionate Central American flair to three World Cups.','story_ar'=>'هندوراس قدّمت روح أمريكا الوسطى الحماسية في ثلاث نسخ من كأس العالم.','stars'=>['Anthony Lozano','Alberth Elis'],'moments'=>['Qualified in 1982, 2010 and 2014']],
                'sv' => ['confed'=>'CONCACAF','story'=>'El Salvador carry the memory of two proud World Cup appearances in 1970 and 1982.','story_ar'=>'السلفادور تحمل ذكرى ظهورين فخورين في كأس العالم 1970 و1982.','stars'=>['Alex Roldán'],'moments'=>['Reached the World Cup in 1970 and 1982']],
                'gt' => ['confed'=>'CONCACAF','story'=>'Guatemala, perennial CONCACAF contenders chasing a maiden World Cup.','story_ar'=>'غواتيمالا، منافس دائم في الكونكاكاف يطارد أول تأهل لكأس العالم.','stars'=>['Rubio Rubin'],'moments'=>['Reached the Hexagonal final round of qualifying']],
                'cw' => ['confed'=>'CONCACAF','story'=>'Curaçao, a tiny island punching far above its weight in CONCACAF.','story_ar'=>'كوراساو، جزيرة صغيرة تتفوق على حجمها في الكونكاكاف.','stars'=>['Leandro Bacuna'],'moments'=>['2017 Caribbean Cup champions']],
                'tt' => ['confed'=>'CONCACAF','story'=>'Trinidad & Tobago made history as the smallest nation at the 2006 World Cup.','story_ar'=>'ترينيداد وتوباغو صنعت التاريخ كأصغر دولة في كأس العالم 2006.','stars'=>['Levi García'],'moments'=>['Qualified for first World Cup in 2006','Held Sweden to a draw in 2006']],
                'ht' => ['confed'=>'CONCACAF','story'=>'Haiti, whose 1974 World Cup goal against Italy ended a record Azzurri shutout.','story_ar'=>'هايتي، وهدفها في مونديال 1974 ضد إيطاليا أنهى سلسلة نظافة شباك قياسية.','stars'=>['Frantzdy Pierrot'],'moments'=>['Emmanuel Sanon scored at the 1974 World Cup']],
                'sr' => ['confed'=>'CONCACAF','story'=>'Suriname, blending Dutch-based talent into a rising CONCACAF force.','story_ar'=>'سورينام، تمزج مواهبها المحترفة في هولندا في قوة صاعدة بالكونكاكاف.','stars'=>['Sheraldo Becker'],'moments'=>['Reached the Nations League knockouts']],

                /* ---- CONMEBOL ---- */
                'ar' => ['confed'=>'CONMEBOL','story'=>'Reigning world champions led by Lionel Messi after their 2022 triumph in Qatar.','story_ar'=>'حامل اللقب العالمي بقيادة ليونيل ميسي بعد تتويج 2022 في قطر.','stars'=>['Lionel Messi','Julián Álvarez','Lautaro Martínez'],'moments'=>['World Cup winners in 1978, 1986 and 2022','Maradona\'s 1986 masterclass']],
                'br' => ['confed'=>'CONMEBOL','story'=>'The only nation to win five World Cups, the spiritual home of the beautiful game.','story_ar'=>'المنتخب الوحيد الفائز بخمسة ألقاب عالمية، والموطن الروحي للكرة الجميلة.','stars'=>['Vinícius Júnior','Rodrygo','Raphinha'],'moments'=>['Five-time champions (1958–2002)','Pelé and Ronaldo eras']],
                'uy' => ['confed'=>'CONMEBOL','story'=>'Two-time champions whose fighting "garra charrúa" spirit defines their game.','story_ar'=>'بطل عالمي مرتين، وروح "غارّا تشارّوا" القتالية تميّز أسلوبه.','stars'=>['Federico Valverde','Darwin Núñez'],'moments'=>['First World Cup winners in 1930','Champions again in 1950 ("Maracanazo")']],
                'co' => ['confed'=>'CONMEBOL','story'=>'Colombia, all rhythm and flair, dazzled the world on their run to the 2014 last eight.','story_ar'=>'كولومبيا، إيقاع ومهارة، أبهرت العالم في مسيرتها لربع نهائي 2014.','stars'=>['James Rodríguez','Luis Díaz'],'moments'=>['James won the 2014 Golden Boot','Quarter-finalists in 2014']],
                'cl' => ['confed'=>'CONMEBOL','story'=>'Chile\'s relentless pressing "golden generation" won back-to-back Copa Américas.','story_ar'=>'جيل تشيلي الذهبي بضغطه المتواصل توّج بكوبا أمريكا مرتين متتاليتين.','stars'=>['Alexis Sánchez'],'moments'=>['Copa América champions 2015 & 2016','Knocked out holders Spain in 2014']],
                'pe' => ['confed'=>'CONMEBOL','story'=>'Peru, with their iconic red sash, returned to the World Cup in 2018 after 36 years.','story_ar'=>'بيرو، بقميصها الأحمر الشهير، عادت إلى كأس العالم 2018 بعد 36 عاماً.','stars'=>['Gianluca Lapadula'],'moments'=>['Quarter-finalists in 1970 and 1978','Ended a 36-year drought in 2018']],
                'py' => ['confed'=>'CONMEBOL','story'=>'Paraguay, famed for steel and grit, reached the 2010 World Cup quarter-finals.','story_ar'=>'باراغواي، المعروفة بصلابتها، بلغت ربع نهائي كأس العالم 2010.','stars'=>['Miguel Almirón'],'moments'=>['Quarter-finalists in 2010']],
                'ec' => ['confed'=>'CONMEBOL','story'=>'Ecuador, powered by the altitude of Quito and a wave of exciting young talent.','story_ar'=>'الإكوادور، مدعومة بارتفاع كيتو وموجة من المواهب الشابة المثيرة.','stars'=>['Moisés Caicedo','Pervis Estupiñán'],'moments'=>['Reached the last 16 in 2006']],
                've' => ['confed'=>'CONMEBOL','story'=>'Venezuela, "La Vinotinto", chasing a long-awaited first World Cup appearance.','story_ar'=>'فنزويلا "لا فينوتينتو"، تطارد أول ظهور تاريخي في كأس العالم.','stars'=>['Salomón Rondón','Yeferson Soteldo'],'moments'=>['Best-ever finish in 2024 Copa América']],
                'bo' => ['confed'=>'CONMEBOL','story'=>'Bolivia, whose high-altitude La Paz fortress troubles the continent\'s giants.','story_ar'=>'بوليفيا، وحصن لاباز المرتفع يُربك عمالقة القارة.','stars'=>['Marcelo Martins'],'moments'=>['Reached the 1994 World Cup']],

                /* ---- UEFA ---- */
                'fr' => ['confed'=>'UEFA','story'=>'Two-time champions and 2022 finalists, blessed with arguably the deepest squad on earth.','story_ar'=>'بطل عالمي مرتين ووصيف 2022، يملك ربما أعمق تشكيلة في العالم.','stars'=>['Kylian Mbappé','Antoine Griezmann','Aurélien Tchouaméni'],'moments'=>['World Cup winners 1998 & 2018','Mbappé\'s 2022 final hat-trick']],
                'es' => ['confed'=>'UEFA','story'=>'The 2010 world champions, masters of tiki-taka and reigning European champions.','story_ar'=>'بطل العالم 2010، أساتذة التيكي-تاكا وحامل لقب أوروبا.','stars'=>['Lamine Yamal','Rodri','Pedri'],'moments'=>['World Cup winners 2010','Euro winners 2008, 2012 & 2024']],
                'de' => ['confed'=>'UEFA','story'=>'Four-time world champions, the byword for tournament efficiency and resilience.','story_ar'=>'بطل العالم أربع مرات، عنوان الكفاءة والصلابة في البطولات.','stars'=>['Jamal Musiala','Florian Wirtz','Kai Havertz'],'moments'=>['World Cup winners 1954, 1974, 1990 & 2014','7-1 vs Brazil in 2014']],
                'pt' => ['confed'=>'UEFA','story'=>'European champions in 2016, balancing the Ronaldo era with a vibrant new generation.','story_ar'=>'بطل أوروبا 2016، يوازن بين حقبة رونالدو وجيل جديد متألق.','stars'=>['Cristiano Ronaldo','Bruno Fernandes','Rafael Leão'],'moments'=>['Euro 2016 champions','Nations League winners 2019']],
                'gb-eng' => ['confed'=>'UEFA','story'=>'1966 world champions and back-to-back Euro finalists chasing a long-awaited trophy.','story_ar'=>'بطل العالم 1966 ووصيف يورو مرتين متتاليتين يطارد لقباً طال انتظاره.','stars'=>['Harry Kane','Jude Bellingham','Bukayo Saka'],'moments'=>['World Cup winners 1966','Euro 2020 & 2024 finalists']],
                'gb-sct' => ['confed'=>'UEFA','story'=>'Scotland, the Tartan Army, bringing fierce passion back to major tournaments.','story_ar'=>'اسكتلندا، الجيش التارتاني، يعيد الشغف الكبير إلى البطولات الكبرى.','stars'=>['Andy Robertson','Scott McTominay'],'moments'=>['Qualified for Euro 2020 & 2024']],
                'gb-wls' => ['confed'=>'UEFA','story'=>'Wales reached the Euro 2016 semi-finals and ended a 64-year World Cup wait in 2022.','story_ar'=>'ويلز بلغت نصف نهائي يورو 2016 وأنهت غياباً عن المونديال دام 64 عاماً في 2022.','stars'=>['Harry Wilson','Brennan Johnson'],'moments'=>['Euro 2016 semi-finalists','Returned to the World Cup in 2022']],
                'nl' => ['confed'=>'UEFA','story'=>'Inventors of "Total Football" and three-time finalists, always playing with style.','story_ar'=>'مبتكرو "الكرة الشاملة" ووصيف ثلاث مرات، يلعبون دائماً بأناقة.','stars'=>['Virgil van Dijk','Cody Gakpo','Frenkie de Jong'],'moments'=>['World Cup finalists 1974, 1978 & 2010','Cruyff\'s 1974 brilliance']],
                'be' => ['confed'=>'UEFA','story'=>'Belgium\'s "golden generation" peaked with a third-place finish at the 2018 World Cup.','story_ar'=>'الجيل الذهبي لبلجيكا بلغ ذروته بالمركز الثالث في مونديال 2018.','stars'=>['Kevin De Bruyne','Romelu Lukaku','Jérémy Doku'],'moments'=>['Third place at the 2018 World Cup']],
                'it' => ['confed'=>'UEFA','story'=>'Four-time world champions and Euro 2020 winners, masters of defensive artistry.','story_ar'=>'بطل العالم أربع مرات وبطل يورو 2020، أساتذة فن الدفاع.','stars'=>['Gianluigi Donnarumma','Federico Chiesa'],'moments'=>['World Cup winners 1934, 1938, 1982 & 2006','Euro 2020 champions']],
                'hr' => ['confed'=>'UEFA','story'=>'Croatia, midfield maestros who reached the 2018 final and 2022 semi-finals.','story_ar'=>'كرواتيا، أساتذة الوسط الذين بلغوا نهائي 2018 ونصف نهائي 2022.','stars'=>['Luka Modrić','Joško Gvardiol'],'moments'=>['World Cup finalists 2018','Third place in 2022']],
                'ch' => ['confed'=>'UEFA','story'=>'Switzerland, the model of consistency, regularly reaching the World Cup knockouts.','story_ar'=>'سويسرا، نموذج الثبات، تبلغ أدوار الإقصاء في المونديال بانتظام.','stars'=>['Granit Xhaka','Manuel Akanji'],'moments'=>['Beat France on penalties in 2022','Last-16 regulars']],
                'dk' => ['confed'=>'UEFA','story'=>'Denmark, the fairytale Euro 92 champions, now a tough, cohesive modern side.','story_ar'=>'الدنمارك، بطل يورو 92 الأسطوري، منتخب حديث متماسك وصعب المراس.','stars'=>['Christian Eriksen','Rasmus Højlund'],'moments'=>['Euro 1992 champions','Euro 2020 semi-finalists']],
                'se' => ['confed'=>'UEFA','story'=>'Sweden, 1958 finalists and World Cup regulars known for organised, disciplined football.','story_ar'=>'السويد، وصيف 1958 ومشارك دائم معروف بكرة منظمة ومنضبطة.','stars'=>['Alexander Isak','Viktor Gyökeres'],'moments'=>['Runners-up at the 1958 World Cup']],
                'no' => ['confed'=>'UEFA','story'=>'Norway, surging behind two of the world\'s most lethal attackers.','story_ar'=>'النرويج، تتقدم بقيادة اثنين من أخطر المهاجمين في العالم.','stars'=>['Erling Haaland','Martin Ødegaard'],'moments'=>['Beat Brazil at the 1998 World Cup']],
                'pl' => ['confed'=>'UEFA','story'=>'Poland, third at two World Cups, still built around one of the era\'s great strikers.','story_ar'=>'بولندا، ثالث في نسختين من المونديال، ما زالت تُبنى حول أحد أعظم المهاجمين.','stars'=>['Robert Lewandowski','Piotr Zieliński'],'moments'=>['Third place in 1974 and 1982']],
                'at' => ['confed'=>'UEFA','story'=>'Austria play an intense, high-pressing brand under a wave of Bundesliga talent.','story_ar'=>'النمسا تلعب أسلوباً ضاغطاً وعالياً بفضل موجة من نجوم البوندسليغا.','stars'=>['David Alaba','Marcel Sabitzer'],'moments'=>['Third at the 1954 World Cup']],
                'rs' => ['confed'=>'UEFA','story'=>'Serbia, technically gifted and direct, packed with attacking quality.','story_ar'=>'صربيا، موهوبة فنياً ومباشرة، تزخر بالجودة الهجومية.','stars'=>['Dušan Vlahović','Aleksandar Mitrović'],'moments'=>['Regular World Cup qualifiers']],
                'ua' => ['confed'=>'UEFA','story'=>'Ukraine, playing with heart and pride for a nation behind them.','story_ar'=>'أوكرانيا، تلعب بقلب وفخر من أجل أمة تقف خلفها.','stars'=>['Mykhailo Mudryk','Artem Dovbyk'],'moments'=>['Quarter-finalists on 2006 debut']],
                'cz' => ['confed'=>'UEFA','story'=>'Czechia, heirs to a proud tradition of finals appearances and elegant football.','story_ar'=>'التشيك، ورثة تقليد عريق من الوصول للنهائيات والكرة الأنيقة.','stars'=>['Patrik Schick','Tomáš Souček'],'moments'=>['Euro 1996 finalists','World Cup finalists 1934 & 1962 (as Czechoslovakia)']],
                'tr' => ['confed'=>'UEFA','story'=>'Türkiye, third at the 2002 World Cup, riding a bold and exciting young generation.','story_ar'=>'تركيا، ثالث مونديال 2002، تركب موجة جيل شاب جريء ومثير.','stars'=>['Arda Güler','Hakan Çalhanoğlu','Kenan Yıldız'],'moments'=>['Third place at the 2002 World Cup','Euro 2024 quarter-finalists']],
                'gr' => ['confed'=>'UEFA','story'=>'Greece, the ultimate underdog story after their shock Euro 2004 triumph.','story_ar'=>'اليونان، قصة الحصان الأسود الكبرى بعد مفاجأة يورو 2004.','stars'=>['Kostas Tsimikas','Konstantinos Mavropanos'],'moments'=>['Euro 2004 champions']],
                'hu' => ['confed'=>'UEFA','story'=>'Hungary, heirs to the legendary "Magical Magyars" of the 1950s, reborn and resilient.','story_ar'=>'المجر، ورثة "المجريين السحرة" الأسطوريين في الخمسينيات، يولدون من جديد.','stars'=>['Dominik Szoboszlai'],'moments'=>['World Cup finalists 1938 & 1954']],
                'ro' => ['confed'=>'UEFA','story'=>'Romania, whose golden 1990s generation reached the 1994 World Cup quarter-finals.','story_ar'=>'رومانيا، وجيلها الذهبي في التسعينيات بلغ ربع نهائي مونديال 1994.','stars'=>['Nicolae Stanciu'],'moments'=>['Quarter-finalists in 1994']],
                'si' => ['confed'=>'UEFA','story'=>'Slovenia, a small nation overachieving behind a world-class goalkeeper.','story_ar'=>'سلوفينيا، دولة صغيرة تحقق ما يفوق إمكاناتها بحارس عالمي.','stars'=>['Jan Oblak','Benjamin Šeško'],'moments'=>['Qualified for 2002 World Cup & Euro 2024']],
                'sk' => ['confed'=>'UEFA','story'=>'Slovakia reached the last 16 on their 2010 World Cup debut, beating holders Italy.','story_ar'=>'سلوفاكيا بلغت دور الـ16 في أول ظهور مونديالي 2010 بفوزها على حامل اللقب إيطاليا.','stars'=>['Milan Škriniar','Stanislav Lobotka'],'moments'=>['Beat Italy at the 2010 World Cup']],
                'is' => ['confed'=>'UEFA','story'=>'Iceland, the smallest nation ever to reach a World Cup, famous for the Viking thunderclap.','story_ar'=>'آيسلندا، أصغر دولة تبلغ كأس العالم، الشهيرة بتصفيق الفايكنغ الرعدي.','stars'=>['Gylfi Sigurðsson'],'moments'=>['Euro 2016 quarter-finalists','Held Argentina in 2018']],
                'ie' => ['confed'=>'UEFA','story'=>'Ireland, whose passionate fans and never-say-die spirit lit up multiple World Cups.','story_ar'=>'أيرلندا، وجماهيرها الشغوفة وروحها التي لا تستسلم أضاءت نسخاً من المونديال.','stars'=>['Evan Ferguson'],'moments'=>['Quarter-finalists in 1990']],
                'al' => ['confed'=>'UEFA','story'=>'Albania, whose red-and-black army brings huge passion to the major stage.','story_ar'=>'ألبانيا، وجيشها الأحمر والأسود يجلب شغفاً هائلاً إلى المسرح الكبير.','stars'=>['Kristjan Asllani'],'moments'=>['Debuted at Euro 2016']],
                'ba' => ['confed'=>'UEFA','story'=>'Bosnia & Herzegovina, technically rich and proud of their 2014 World Cup debut.','story_ar'=>'البوسنة والهرسك، غنية فنياً وفخورة بأول ظهور مونديالي 2014.','stars'=>['Edin Džeko'],'moments'=>['First World Cup appearance in 2014']],
                'mk' => ['confed'=>'UEFA','story'=>'North Macedonia stunned Europe by knocking out Italy in 2022 qualifying.','story_ar'=>'مقدونيا الشمالية صدمت أوروبا بإقصاء إيطاليا في تصفيات 2022.','stars'=>['Eljif Elmas'],'moments'=>['Beat Italy in 2022 qualifying','Debuted at Euro 2020']],
                'ge' => ['confed'=>'UEFA','story'=>'Georgia, a rising force who reached the Euro 2024 last 16 on their major-tournament debut.','story_ar'=>'جورجيا، قوة صاعدة بلغت دور الـ16 في يورو 2024 بأول ظهور لها.','stars'=>['Khvicha Kvaratskhelia'],'moments'=>['Euro 2024 round of 16 on debut']],

                /* ---- AFC ---- */
                'jp' => ['confed'=>'AFC','story'=>'Japan, Asia\'s benchmark, famous for stunning World Cup wins over Germany and Spain.','story_ar'=>'اليابان، معيار آسيا، الشهيرة بفوزها المذهل على ألمانيا وإسبانيا في المونديال.','stars'=>['Takefusa Kubo','Kaoru Mitoma','Wataru Endo'],'moments'=>['Beat Germany & Spain in 2022','Reached the last 16 four times']],
                'kr' => ['confed'=>'AFC','story'=>'South Korea, 2002 semi-finalists and the most consistent qualifier in Asia.','story_ar'=>'كوريا الجنوبية، نصف نهائي 2002 وأكثر منتخب آسيوي ثباتاً في التأهل.','stars'=>['Son Heung-min','Lee Kang-in'],'moments'=>['Semi-finalists as hosts in 2002','Beat Germany in 2018']],
                'au' => ['confed'=>'AFC','story'=>'Australia, the battling Socceroos, who reached the last 16 in 2006 and 2022.','story_ar'=>'أستراليا، السوكاروز المقاتلون، الذين بلغوا دور الـ16 في 2006 و2022.','stars'=>['Mathew Leckie','Jackson Irvine'],'moments'=>['Round of 16 in 2006 and 2022']],
                'sa' => ['confed'=>'AFC','story'=>'Saudi Arabia, the Green Falcons, who famously toppled champions Argentina in 2022.','story_ar'=>'السعودية، الصقور الخضر، الذين أسقطوا حامل اللقب الأرجنتين في 2022.','stars'=>['Salem Al-Dawsari','Firas Al-Buraikan'],'moments'=>['Beat Argentina in 2022','Reached the last 16 in 1994']],
                'qa' => ['confed'=>'AFC','story'=>'Qatar, 2022 World Cup hosts and back-to-back Asian Cup champions.','story_ar'=>'قطر، مستضيف مونديال 2022 وبطل كأس آسيا مرتين متتاليتين.','stars'=>['Akram Afif','Almoez Ali'],'moments'=>['Asian Cup champions 2019 & 2023']],
                'ir' => ['confed'=>'AFC','story'=>'Iran, one of Asia\'s strongest sides, regular World Cup qualifiers with a fierce defence.','story_ar'=>'إيران، أحد أقوى منتخبات آسيا، متأهل دائم للمونديال بدفاع شرس.','stars'=>['Mehdi Taremi','Alireza Jahanbakhsh'],'moments'=>['Beat USA at the 1998 World Cup']],
                'iq' => ['confed'=>'AFC','story'=>'Iraq, the Lions of Mesopotamia, whose 2007 Asian Cup win united a nation.','story_ar'=>'العراق، أسود الرافدين، وفوزهم بكأس آسيا 2007 وحّد أمة.','stars'=>['Aymen Hussein'],'moments'=>['Asian Cup champions 2007']],
                'ae' => ['confed'=>'AFC','story'=>'United Arab Emirates, Gulf football pioneers chasing a return to the World Cup.','story_ar'=>'الإمارات، روّاد كرة الخليج، تطارد العودة إلى كأس العالم.','stars'=>['Caio Canedo'],'moments'=>['Reached the 1990 World Cup','Asian Cup hosts & semi-finalists 2019']],
                'jo' => ['confed'=>'AFC','story'=>'Jordan stunned Asia by reaching the 2023 Asian Cup final, a historic first.','story_ar'=>'الأردن فاجأ آسيا بالوصول إلى نهائي كأس آسيا 2023، إنجاز تاريخي أول.','stars'=>['Mousa Al-Taamari','Yazan Al-Naimat'],'moments'=>['Asian Cup runners-up 2023']],
                'om' => ['confed'=>'AFC','story'=>'Oman, Gulf Cup champions known for their disciplined, well-drilled football.','story_ar'=>'عُمان، بطل كأس الخليج المعروف بكرته المنضبطة والمنظمة.','stars'=>['Muhsen Al-Ghassani'],'moments'=>['Multiple Gulf Cup titles']],
                'uz' => ['confed'=>'AFC','story'=>'Uzbekistan, Central Asia\'s rising power, qualifying for their first-ever World Cup.','story_ar'=>'أوزبكستان، قوة آسيا الوسطى الصاعدة، تتأهل لأول كأس عالم في تاريخها.','stars'=>['Eldor Shomurodov','Abbosbek Fayzullaev'],'moments'=>['First-ever World Cup qualification']],
                'cn' => ['confed'=>'AFC','story'=>'China, football\'s vast sleeping giant, dreaming of a return to the World Cup.','story_ar'=>'الصين، العملاق النائم في كرة القدم، تحلم بالعودة إلى كأس العالم.','stars'=>['Wu Lei'],'moments'=>['Reached the 2002 World Cup']],
                'in' => ['confed'=>'AFC','story'=>'India, a sleeping giant with huge potential and a passionate, growing fan base.','story_ar'=>'الهند، عملاق نائم بإمكانات هائلة وقاعدة جماهيرية شغوفة ومتنامية.','stars'=>['Sunil Chhetri'],'moments'=>['Multiple-time South Asian champions']],
                'id' => ['confed'=>'AFC','story'=>'Indonesia, riding fervent support and a wave of diaspora talent toward the World Cup.','story_ar'=>'إندونيسيا، تركب دعماً جارفاً وموجة مواهب من المغتربين نحو كأس العالم.','stars'=>['Marselino Ferdinan'],'moments'=>['Reached the 2023 Asian Cup knockouts']],
                'ps' => ['confed'=>'AFC','story'=>'Palestine, whose national team carries the hopes and pride of millions.','story_ar'=>'فلسطين، ومنتخبها يحمل آمال وفخر الملايين.','stars'=>['Oday Dabbagh'],'moments'=>['Reached the 2023 Asian Cup knockouts']],
                'bh' => ['confed'=>'AFC','story'=>'Bahrain, 2019 Gulf Cup and Arabian Gulf Cup champions, organised and ambitious.','story_ar'=>'البحرين، بطل خليجي 2019، منتخب منظم وطموح.','stars'=>['Mohamed Marhoon'],'moments'=>['Gulf Cup champions 2019']],
                'kw' => ['confed'=>'AFC','story'=>'Kuwait, 1980 Asian Cup winners and 1982 World Cup participants.','story_ar'=>'الكويت، بطل آسيا 1980 ومشارك في مونديال 1982.','stars'=>['Yousef Nasser'],'moments'=>['Asian Cup champions 1980','Reached the 1982 World Cup']],
                'vn' => ['confed'=>'AFC','story'=>'Vietnam, Southeast Asia\'s standard-bearers and 2018 AFF Cup champions.','story_ar'=>'فيتنام، حاملة لواء جنوب شرق آسيا وبطل كأس آسيان 2018.','stars'=>['Nguyễn Quang Hải'],'moments'=>['Reached the 2022 WC qualifying final round']],
                'th' => ['confed'=>'AFC','story'=>'Thailand, the "War Elephants", perennial Southeast Asian champions chasing a first World Cup.','story_ar'=>'تايلاند، "أفيال الحرب"، بطل دائم لجنوب شرق آسيا يطارد أول مونديال.','stars'=>['Chanathip Songkrasin'],'moments'=>['Multiple AFF Championship titles']],

                /* ---- CAF ---- */
                'ma' => ['confed'=>'CAF','story'=>'Morocco made history as the first African and Arab nation to reach a World Cup semi-final in 2022.','story_ar'=>'المغرب صنع التاريخ كأول منتخب عربي وإفريقي يبلغ نصف نهائي كأس العالم 2022.','stars'=>['Achraf Hakimi','Brahim Díaz','Youssef En-Nesyri'],'moments'=>['Semi-finalists in 2022','Beat Spain & Portugal in 2022']],
                'sn' => ['confed'=>'CAF','story'=>'Senegal, reigning African champions and one of the continent\'s most powerful sides.','story_ar'=>'السنغال، بطل إفريقيا الحالي وأحد أقوى منتخبات القارة.','stars'=>['Sadio Mané','Nicolas Jackson'],'moments'=>['AFCON champions 2021','Quarter-finalists in 2002']],
                'gh' => ['confed'=>'CAF','story'=>'Ghana, the Black Stars, who came within a penalty of the 2010 World Cup semi-finals.','story_ar'=>'غانا، النجوم السوداء، الذين كانوا على بُعد ركلة جزاء من نصف نهائي 2010.','stars'=>['Mohammed Kudus','Thomas Partey'],'moments'=>['Quarter-finalists in 2010','Four-time AFCON champions']],
                'ng' => ['confed'=>'CAF','story'=>'Nigeria, the Super Eagles, African royalty famed for flair and explosive attackers.','story_ar'=>'نيجيريا، النسور الخارقة، من نبلاء إفريقيا المعروفين بالمهارة والمهاجمين المتفجرين.','stars'=>['Victor Osimhen','Ademola Lookman'],'moments'=>['Olympic gold 1996','Three-time AFCON champions']],
                'cm' => ['confed'=>'CAF','story'=>'Cameroon, the Indomitable Lions, whose 1990 run electrified the football world.','story_ar'=>'الكاميرون، الأسود التي لا تُقهر، ومسيرتها في 1990 أبهرت عالم الكرة.','stars'=>['André Onana','Vincent Aboubakar'],'moments'=>['Quarter-finalists in 1990','Beat Brazil in 2022']],
                'eg' => ['confed'=>'CAF','story'=>'Egypt, Africa\'s most successful side with a record seven AFCON titles.','story_ar'=>'مصر، أنجح منتخبات إفريقيا برقم قياسي سبعة ألقاب لكأس الأمم.','stars'=>['Mohamed Salah','Omar Marmoush'],'moments'=>['Record 7 AFCON titles']],
                'dz' => ['confed'=>'CAF','story'=>'Algeria, the Desert Foxes, 2019 African champions and 2014 World Cup last-16 side.','story_ar'=>'الجزائر، ثعالب الصحراء، بطل إفريقيا 2019 ودور الـ16 في مونديال 2014.','stars'=>['Riyad Mahrez','Ismaël Bennacer'],'moments'=>['AFCON champions 2019','Round of 16 in 2014']],
                'tn' => ['confed'=>'CAF','story'=>'Tunisia, the Eagles of Carthage, who beat reigning champions France in 2022.','story_ar'=>'تونس، نسور قرطاج، الذين هزموا حامل اللقب فرنسا في 2022.','stars'=>['Hannibal Mejbri','Youssef Msakni'],'moments'=>['Beat France in 2022','AFCON champions 2004']],
                'ci' => ['confed'=>'CAF','story'=>'Ivory Coast, the Elephants, dramatic home winners of the 2023 Africa Cup of Nations.','story_ar'=>'ساحل العاج، الأفيال، الفائز الدرامي بكأس أمم إفريقيا 2023 على أرضه.','stars'=>['Sébastien Haller','Simon Adingra'],'moments'=>['AFCON champions 2015 & 2023']],
                'za' => ['confed'=>'CAF','story'=>'South Africa, 2010 World Cup hosts, returning with an exciting young Bafana Bafana side.','story_ar'=>'جنوب إفريقيا، مستضيف مونديال 2010، تعود بمنتخب "بافانا بافانا" شاب ومثير.','stars'=>['Lyle Foster','Percy Tau'],'moments'=>['AFCON champions 1996','Hosted the 2010 World Cup']],
                'ml' => ['confed'=>'CAF','story'=>'Mali, blessed with a conveyor belt of talent, chasing a first World Cup appearance.','story_ar'=>'مالي، تملك خط إنتاج للمواهب، تطارد أول ظهور مونديالي.','stars'=>['Yves Bissouma','Amadou Haidara'],'moments'=>['U-17 World Cup finalists 2015']],
                'cv' => ['confed'=>'CAF','story'=>'Cape Verde, the Blue Sharks, a tiny island nation defying the odds in African football.','story_ar'=>'الرأس الأخضر، أسماك القرش الزرقاء، جزيرة صغيرة تتحدى الصعاب في كرة إفريقيا.','stars'=>['Ryan Mendes'],'moments'=>['AFCON quarter-finalists 2013 & 2023']],
                'gn' => ['confed'=>'CAF','story'=>'Guinea, a proud West African side with a rich history of African talent.','story_ar'=>'غينيا، منتخب غرب إفريقي فخور بتاريخ غني من المواهب الإفريقية.','stars'=>['Serhou Guirassy','Naby Keïta'],'moments'=>['AFCON runners-up 1976']],
                'cd' => ['confed'=>'CAF','story'=>'DR Congo, two-time African champions with deep reserves of attacking talent.','story_ar'=>'الكونغو الديمقراطية، بطل إفريقيا مرتين بمخزون عميق من المواهب الهجومية.','stars'=>['Yoane Wissa','Cédric Bakambu'],'moments'=>['AFCON champions 1968 & 1974','Semi-finalists 2024']],
                'ga' => ['confed'=>'CAF','story'=>'Gabon, the Panthers, who lit up Africa with a generation of attacking flair.','story_ar'=>'الغابون، الفهود، الذين أضاءوا إفريقيا بجيل من المهارة الهجومية.','stars'=>['Pierre-Emerick Aubameyang'],'moments'=>['AFCON quarter-finalists 2012']],
                'ao' => ['confed'=>'CAF','story'=>'Angola, the Black Antelopes, whose 2006 World Cup debut thrilled the nation.','story_ar'=>'أنغولا، الظباء السوداء، وأول ظهور مونديالي 2006 أسعد الأمة.','stars'=>['Gelson Dala'],'moments'=>['Reached the 2006 World Cup']],
                'zm' => ['confed'=>'CAF','story'=>'Zambia, the Chipolopolo, whose emotional 2012 AFCON triumph moved the continent.','story_ar'=>'زامبيا، تشيبولوبولو، وتتويجها العاطفي بكأس إفريقيا 2012 أبكى القارة.','stars'=>['Patson Daka'],'moments'=>['AFCON champions 2012']],
                'bf' => ['confed'=>'CAF','story'=>'Burkina Faso, the Stallions, AFCON 2013 finalists and consistent African contenders.','story_ar'=>'بوركينا فاسو، الفحول، وصيف كأس إفريقيا 2013 ومنافس إفريقي دائم.','stars'=>['Bertrand Traoré'],'moments'=>['AFCON runners-up 2013']],
                'gq' => ['confed'=>'CAF','story'=>'Equatorial Guinea, surprise package that stunned bigger names at AFCON 2023.','story_ar'=>'غينيا الاستوائية، مفاجأة صدمت الكبار في كأس إفريقيا 2023.','stars'=>['Emilio Nsue'],'moments'=>['AFCON semi-finalists 2015 (hosts)']],

                /* ---- OFC ---- */
                'nz' => ['confed'=>'OFC','story'=>'New Zealand, the All Whites, who went unbeaten at the 2010 World Cup.','story_ar'=>'نيوزيلندا، "أول وايتس"، الذين خرجوا بلا خسارة من مونديال 2010.','stars'=>['Chris Wood'],'moments'=>['Unbeaten at the 2010 World Cup','Oceania\'s dominant side']],
                'fj' => ['confed'=>'OFC','story'=>'Fiji, a passionate Pacific island side chasing a historic first World Cup.','story_ar'=>'فيجي، جزيرة هادي الشغوفة تطارد أول مونديال تاريخي.','stars'=>['Roy Krishna'],'moments'=>['Reached the 2016 Olympic football tournament']],
                'pg' => ['confed'=>'OFC','story'=>'Papua New Guinea, OFC Nations Cup runners-up and an emerging Pacific force.','story_ar'=>'بابوا غينيا الجديدة، وصيف كأس أوقيانوسيا وقوة هادية صاعدة.','stars'=>['Raymond Gunemba'],'moments'=>['OFC Nations Cup runners-up 2016']],
                'nc' => ['confed'=>'OFC','story'=>'New Caledonia, technically gifted islanders pushing for a first World Cup.','story_ar'=>'كاليدونيا الجديدة، جزيريون موهوبون فنياً يسعون لأول مونديال.','stars'=>['César Zeoula'],'moments'=>['OFC Nations Cup semi-finalists']],
                'pf' => ['confed'=>'OFC','story'=>'Tahiti, the dream story of Oceania, who reached the 2013 Confederations Cup.','story_ar'=>'تاهيتي، قصة حلم أوقيانوسيا، التي بلغت كأس القارات 2013.','stars'=>['Teaonui Tehau'],'moments'=>['OFC Nations Cup champions 2012']],
            ];
        }
        if ($code === '') return $m;
        $code = strtolower(trim($code));
        return $m[$code] ?? [];
    }
}
